// AUTO-GENERATED game catalog.
// Featured games (hosted outside the offline pack) appear first, followed by
// every game from the Offline-HTML-Games-Pack "offline" folder.

export interface Game {
  id: string
  title: string
  url: string
  image?: string
}

export const games: Game[] = [
  { id: "gunspin", title: "GunSpin", url: "https://thomasrhys.github.io/angry-games/gunspin", image: "/images/gunspin.webp" },
  { id: "bitlife-online", title: "BitLife", url: "https://thomasrhys.github.io/angry-games/bitlife", image: "/images/bitlife.webp" },
  { id: "cherry-pickr", title: "Cherry Pickr", url: "https://thomasrhys.github.io/cherry-pickr" },
  { id: "cherry-picker-2", title: "Cherry Picker 2", url: "https://thomasrhys.github.io/cherry-picker-by-at12" },
  { id: "fnf", title: "Friday Night Funkin'", url: "https://thomasrhysfnf.netlify.app", image: "/images/friday-night-funkin.jpg" },
  { id: "slide-down", title: "Slide Down", url: "https://gamea.azgame.io/slide-down", image: "/images/slidedown.png" },
  { id: "slope-2-az", title: "Slope 2", url: "https://game.azgame.io/slope-2", image: "/images/slope-2-az.webp" },
  { id: "slope-az", title: "Slope", url: "https://azgames.io/slope.embed", image: "/images/Slope-az.webp" },
  { id: "1-12", title: "Minecraft 1.12", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/1.12.html", image: "/images/minecraft-cover-1.jpg" },
  { id: "1-5", title: "Minecraft 1.5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/1.5.html", image: "/images/minecraft-cover-1.jpg" },
  { id: "1-8", title: "Minecraft 1.8", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/1.8.html", image: "/images/minecraft-cover-1.jpg" },
  { id: "10minutestilldawn", title: "10 Minutes Till Dawn", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/10minutestilldawn.html", image: "/images/10 Minutes Till Dawn.jpg" },
  { id: "12minibattles", title: "12 MiniBattles", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/12minibattles.html", image: "/images/12mb.jpg" },
  { id: "1on1soccer", title: "1 on 1 Soccer", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/1on1soccer.html", image: "/images/11soccer.jpg" },
  { id: "1on1tennis", title: "1 on 1 Tennis", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/1on1tennis.html", image: "/images/11tennis.png" },
  { id: "1v1-lol", title: "1v1.LOL", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/1v1.lol.html", image: "/images/1v1lol.png" },
  { id: "2048", title: "2048", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/2048.html" },
  { id: "2048cupcakes", title: "2048 Cupcakes", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/2048cupcakes.html" },
  { id: "3dflightsimulator", title: "3D Flight Simulator", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/3Dflightsimulator.html" },
  { id: "8ballclassic", title: "8 Ball Classic", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/8ballclassic.html" },
  { id: "alpha-1-2-6", title: "Minecraft Alpha 1.2.6", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/Alpha_1.2.6.html", image: "/images/minecraft-cover-2.png" },
  { id: "beta-1-3", title: "Minecraft Beta 1.3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/Beta_1.3.html", image: "/images/minecraft-cover-2.png" },
  { id: "indev", title: "Minecraft Indev", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/Indev.html", image: "/images/minecraft-cover-2.png" },
  { id: "agariolite", title: "Agar.io Lite", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/agariolite.html" },
  { id: "ageofwar", title: "Age of War", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ageofwar.html" },
  { id: "ageofwar2", title: "Age of War 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ageofwar2.html" },
  { id: "agesofconflict", title: "Ages of Conflict", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/agesofconflict.html" },
  { id: "amongus", title: "Among Us", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/amongus.html" },
  { id: "angrybirds", title: "Angry Birds", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/angrybirds.html" },
  { id: "angrybirdsshowdown", title: "Angry Birds Showdown", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/angrybirdsshowdown.html" },
  { id: "angrybirdsspace", title: "Angry Birds Space", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/angrybirdsspace.html" },
  { id: "awesometanks", title: "Awesome Tanks", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/awesometanks.html" },
  { id: "awesometanks2", title: "Awesome Tanks 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/awesometanks2.html" },
  { id: "backrooms", title: "Backrooms", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/backrooms.html" },
  { id: "baconmaydie", title: "Bacon May Die", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/baconmaydie.html" },
  { id: "badicecream", title: "Bad Ice Cream", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/badicecream.html" },
  { id: "badicecream2", title: "Bad Ice Cream 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/badicecream2.html" },
  { id: "badicecream3", title: "Bad Ice Cream 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/badicecream3.html" },
  { id: "badparenting", title: "Bad Parenting", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/badparenting.html" },
  { id: "badpiggies", title: "Bad Piggies", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/badpiggies.html" },
  { id: "baldisbasics", title: "Baldi's Basics", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/baldisbasics.html" },
  { id: "baseballbros", title: "Baseball Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/baseballbros.html" },
  { id: "basketballlegends", title: "Basketball Legends", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/basketballlegends.html" },
  { id: "basketballstars", title: "Basketball Stars", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/basketballstars.html" },
  { id: "basketbros", title: "Basket Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/basketbros.html" },
  { id: "basketrandom", title: "Basket Random", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/basketrandom.html" },
  { id: "bitlife", title: "BitLife", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bitlife.html" },
  { id: "bitplanes", title: "Bitplanes", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bitplanes.htm" },
  { id: "blockysnakes", title: "Blocky Snakes", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/blockysnakes.html" },
  { id: "bloonstd", title: "Bloons TD", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bloonsTD.html", image: "/images/Btd.jpg" },
  { id: "bloonstd2", title: "Bloons TD 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bloonsTD2.html", image: "/images/Btd2.webp" },
  { id: "bloonstd3", title: "Bloons TD 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bloonsTD3.html", image: "/images/btd3.jpg" },
  { id: "bloonstd4", title: "Bloons TD 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bloonsTD4.html", image: "/images/btd4.jpeg" },
  { id: "bloonstd5", title: "Bloons TD 5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bloonsTD5.html", image: "/images/btd5.jpg" },
  { id: "bloxorz", title: "Bloxorz", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bloxorz.html" },
  { id: "blumgiracers", title: "Blumgi Racers", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/blumgiracers.html" },
  { id: "blumgirocket", title: "Blumgi Rocket", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/blumgirocket.html" },
  { id: "bobtherobber", title: "Bob the Robber", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bobtherobber.html" },
  { id: "bobtherobber2", title: "Bob the Robber 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bobtherobber2.html" },
  { id: "bobtherobber5", title: "Bob the Robber 5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bobtherobber5.html" },
  { id: "bouncymotors", title: "Bouncy Motors", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bouncymotors.html" },
  { id: "bowmasters", title: "Bowmasters", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bowmasters.html" },
  { id: "boxingrandom", title: "Boxing Random", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/boxingrandom.htm" },
  { id: "breakingthebank", title: "Breaking the Bank", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/breakingthebank.html" },
  { id: "bubbleshooter", title: "Bubble Shooter", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/bubbleshooter.html" },
  { id: "candycrush", title: "Candy Crush", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/candycrush.html" },
  { id: "capybaraclicker", title: "Capybara Clicker", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/capybaraclicker.html" },
  { id: "cardrawing", title: "Car Drawing", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/cardrawing.html" },
  { id: "carkingarena", title: "Car King Arena", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/carkingarena.html" },
  { id: "chess", title: "Chess", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/chess.html" },
  { id: "choppyorc", title: "Choppy Orc", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/choppyorc.html" },
  { id: "circloo", title: "circloO", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/circloO.html" },
  { id: "circloo2", title: "circloO 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/circloO2.html" },
  { id: "clashofvikings", title: "Clash of Vikings", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/clashofvikings.html" },
  { id: "cleanupio", title: "Cleanup.io", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/cleanupio.html" },
  { id: "clusterrush", title: "Cluster Rush", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/clusterrush.html" },
  { id: "cookieclicker", title: "Cookie Clicker", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/cookieclicker.htm" },
  { id: "crazycars", title: "Crazy Cars", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/crazycars.html" },
  { id: "crazycattle3d", title: "Crazy Cattle 3D", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/crazycattle3D.html" },
  { id: "crazycrashlanding", title: "Crazy Crash Landing", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/crazycrashlanding.html" },
  { id: "crazymotorcycle", title: "Crazy Motorcycle", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/crazymotorcycle.html" },
  { id: "crossyroad", title: "Crossy Road", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/crossyroad.htm" },
  { id: "cuttherope", title: "Cut the Rope", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/cuttherope.html" },
  { id: "dadish", title: "Dadish", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/dadish.html" },
  { id: "dadish2", title: "Dadish 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/dadish2.html" },
  { id: "dadish3", title: "Dadish 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/dadish3.html" },
  { id: "deathchase", title: "Death Chase", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/deathchase.html" },
  { id: "deathrun3d", title: "Death Run 3D", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/deathrun3D.html" },
  { id: "demolitionderbycrashracing", title: "Demolition Derby Crash Racing", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/demolitionderbycrashracing.html" },
  { id: "doodlejump", title: "Doodle Jump", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/doodlejump.html" },
  { id: "drawclimber", title: "Draw Climber", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/drawclimber.html" },
  { id: "dreadheadparkour", title: "Dreadhead Parkour", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/dreadheadparkour.htm" },
  { id: "driftboss", title: "Drift Boss", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/driftboss.htm" },
  { id: "drivemad", title: "Drive Mad", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/drivemad.htm" },
  { id: "ducklife", title: "Duck Life", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ducklife.html" },
  { id: "ducklife2", title: "Duck Life 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ducklife2.html" },
  { id: "ducklife3", title: "Duck Life 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ducklife3.html" },
  { id: "ducklife4", title: "Duck Life 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ducklife4.html" },
  { id: "ducklife5", title: "Duck Life 5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ducklife5.html" },
  { id: "ducklingsio", title: "Ducklings.io", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ducklingsio.html" },
  { id: "eagleride", title: "Eagle Ride", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/eagleride.html" },
  { id: "earntodie", title: "Earn to Die", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/earntodie.html" },
  { id: "earntodie2", title: "Earn to Die 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/earntodie2.html" },
  { id: "eggycar", title: "Eggy Car", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/eggycar.html" },
  { id: "elasticface", title: "Elastic Face", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/elasticface.htm" },
  { id: "escaperoad", title: "Escape Road", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/escaperoad.html", image: "/images/escape-road.jpg" },
  { id: "escaperoad2", title: "Escape Road 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/escaperoad2.html" },
  { id: "escaperoad3", title: "Escape Road 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/escaperoad3.html" },
  { id: "escaperoadcity2", title: "Escape Road City 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/escaperoadcity2.html" },
  { id: "escapingtheprison", title: "Escaping the Prison", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/escapingtheprison.html" },
  { id: "evilglitch", title: "Evil Glitch", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/evilglitch.html" },
  { id: "fancypantsadventure", title: "Fancy Pants Adventure", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fancypantsadventure.html" },
  { id: "fancypantsadventure2", title: "Fancy Pants Adventure 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fancypantsadventure2.html" },
  { id: "fireboyandwatergirl", title: "Fireboy and Watergirl", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fireboyandwatergirl.html" },
  { id: "fireboyandwatergirl2", title: "Fireboy and Watergirl 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fireboyandwatergirl2.html" },
  { id: "fireboyandwatergirl3", title: "Fireboy and Watergirl 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fireboyandwatergirl3.html" },
  { id: "fireboyandwatergirl4", title: "Fireboy and Watergirl 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fireboyandwatergirl4.html" },
  { id: "flappybird", title: "Flappy Bird", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/flappybird.html" },
  { id: "floodrunner2", title: "Flood Runner 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/floodrunner2.html" },
  { id: "floodrunner3", title: "Flood Runner 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/floodrunner3.html" },
  { id: "floodrunner4", title: "Flood Runner 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/floodrunner4.html" },
  { id: "fnaf", title: "Five Nights at Freddy's", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fnaf.html" },
  { id: "fnaf2", title: "Five Nights at Freddy's 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fnaf2.html" },
  { id: "fnaf3", title: "Five Nights at Freddy's 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fnaf3.html" },
  { id: "fnaf4", title: "Five Nights at Freddy's 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fnaf4.html" },
  { id: "footballbros", title: "Football Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/footballbros.html" },
  { id: "footballlegends", title: "Football Legends", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/footballlegends.html" },
  { id: "freerider3", title: "Free Rider 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/freerider3.html" },
  { id: "fruitninja", title: "Fruit Ninja", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/fruitninja.html" },
  { id: "funnybattle", title: "Funny Battle", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/funnybattle.html" },
  { id: "funnybattle2", title: "Funny Battle 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/funnybattle2.html" },
  { id: "funnymadracing", title: "Funny Mad Racing", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/funnymadracing.html" },
  { id: "funnyshooter2", title: "Funny Shooter 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/funnyshooter2.html" },
  { id: "geometrydash", title: "Geometry Dash", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/geometrydash.html", image: "/images/geometry-dash.jpg" },
  { id: "geometrydashlite", title: "Geometry Dash Lite", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/geometrydashlite.html", image: "/images/geometry-dash.jpg" },
  { id: "geometryvibes", title: "Geometry Vibes", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/geometryvibes.html" },
  { id: "getawayshootout", title: "Getaway Shootout", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/getawayshootout.htm" },
  { id: "getontop", title: "Get on Top", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/getontop.html" },
  { id: "gladihoppers", title: "Gladihoppers", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/gladihoppers.html" },
  { id: "googlebaseball", title: "Google Baseball", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/googlebaseball.html" },
  { id: "googledino", title: "Google Dino", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/googledino.html" },
  { id: "granny", title: "Granny", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/granny.html" },
  { id: "granny2", title: "Granny 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/granny2.html" },
  { id: "guesstheiranswer", title: "Guess Their Answer", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/guesstheiranswer.html" },
  { id: "hanger2", title: "Hanger 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/hanger2.html" },
  { id: "happywheels", title: "Happy Wheels", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/happywheels.html" },
  { id: "helixjump", title: "Helix Jump", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/helixjump.html" },
  { id: "highwaytraffic", title: "Highway Traffic", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/highwaytraffic.html" },
  { id: "hillclimbracinglite", title: "Hill Climb Racing Lite", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/hillclimbracinglite.html" },
  { id: "holeio", title: "Hole.io", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/holeio.html" },
  { id: "houseofhazards", title: "House of Hazards", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/houseofhazards.html" },
  { id: "hoverracerdrive", title: "Hover Racer Drive", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/hoverracerdrive.html" },
  { id: "idlebreakout", title: "Idle Breakout", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/idlebreakout.html" },
  { id: "ironsnout", title: "Iron Snout", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ironsnout.html" },
  { id: "jetpackjoyride", title: "Jetpack Joyride", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/jetpackjoyride.html" },
  { id: "johnnytrigger", title: "Johnny Trigger", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/johnnytrigger.html" },
  { id: "jumpingshell", title: "Jumping Shell", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/jumpingshell.html" },
  { id: "karatebros", title: "Karate Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/karatebros.html" },
  { id: "kartbros", title: "Kart Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/kartbros.html" },
  { id: "learntofly", title: "Learn to Fly", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/learntofly.html" },
  { id: "learntofly2", title: "Learn to Fly 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/learntofly2.html" },
  { id: "learntofly3", title: "Learn to Fly 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/learntofly3.html" },
  { id: "learntoflyidle", title: "Learn to Fly Idle", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/learntoflyidle.html" },
  { id: "leveldevil", title: "Level Devil", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/leveldevil.html" },
  { id: "madalinstuntcars2", title: "Madalin Stunt Cars 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/madalinstuntcars2.html" },
  { id: "melonplayground", title: "Melon Playground", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/melonplayground.html" },
  { id: "mergeroundracers", title: "Merge Round Racers", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/mergeroundracers.html" },
  { id: "minesweeper", title: "Minesweeper", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/minesweeper.html" },
  { id: "monkeymart", title: "Monkey Mart", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/monkeymart.htm" },
  { id: "monstertracks", title: "Monster Tracks", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/monstertracks.html" },
  { id: "motox3m", title: "Moto X3M", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/motox3m.htm" },
  { id: "motox3m2", title: "Moto X3M 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/motox3m2.html" },
  { id: "motox3m3", title: "Moto X3M 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/motox3m3.html" },
  { id: "motox3mpoolparty", title: "Moto X3M Pool Party", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/motox3mpoolparty.html" },
  { id: "motox3mspookyland", title: "Moto X3M Spooky Land", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/motox3mspookyland.html" },
  { id: "motox3mwinter", title: "Moto X3M Winter", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/motox3mwinter.html" },
  { id: "noobminer", title: "Noob Miner", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/noobminer.html" },
  { id: "oppositeday", title: "Opposite Day", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/oppositeday.html" },
  { id: "ovo", title: "OvO", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ovo.html" },
  { id: "ovo2", title: "OvO 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ovo2.html" },
  { id: "ovo3dimensions", title: "OvO 3 Dimensions", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ovo3dimensions.html" },
  { id: "pacman", title: "Pac-Man", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/pacman.html" },
  { id: "papasbakeria", title: "Papa's Bakeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papasbakeria.html" },
  { id: "papasburgeria", title: "Papa's Burgeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papasburgeria.html" },
  { id: "papascheeseria", title: "Papa's Cheeseria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papascheeseria.html" },
  { id: "papascupcakeria", title: "Papa's Cupcakeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papascupcakeria.html" },
  { id: "papasdonuteria", title: "Papa's Donuteria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papasdonuteria.html" },
  { id: "papasfreezeria", title: "Papa's Freezeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papasfreezeria.html" },
  { id: "papashotdoggeria", title: "Papa's Hot Doggeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papashotdoggeria.html" },
  { id: "papaspancakeria", title: "Papa's Pancakeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papaspancakeria.html" },
  { id: "papaspastaria", title: "Papa's Pastaria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papaspastaria.html" },
  { id: "papaspizzeria", title: "Papa's Pizzeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papaspizzeria.html" },
  { id: "papasscooperia", title: "Papa's Scooperia", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papasscooperia.html" },
  { id: "papassushiria", title: "Papa's Sushiria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papassushiria.html" },
  { id: "papastacomia", title: "Papa's Taco Mia", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papastacomia.html" },
  { id: "papaswingeria", title: "Papa's Wingeria", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/papaswingeria.html" },
  { id: "paperio2", title: "Paper.io 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/paperio2.htm" },
  { id: "parkingfury", title: "Parking Fury", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/parkingfury.html" },
  { id: "parkingfury2", title: "Parking Fury 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/parkingfury2.html" },
  { id: "parkingfury3", title: "Parking Fury 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/parkingfury3.html" },
  { id: "picosschool", title: "Pico's School", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/picosschool.html" },
  { id: "pingpongchaos", title: "Ping Pong Chaos", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/pingpongchaos.html" },
  { id: "pixelspeedrun", title: "Pixel Speedrun", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/pixelspeedrun.html" },
  { id: "plantsvszombies", title: "Plants vs Zombies", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/plantsvszombies.html" },
  { id: "plonky", title: "Plonky", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/plonky.html" },
  { id: "polytrack", title: "PolyTrack", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/polytrack.html" },
  { id: "poorbunny", title: "Poor Bunny", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/poorbunny.html" },
  { id: "pou", title: "Pou", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/pou.html" },
  { id: "ragdollarchers", title: "Ragdoll Archers", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ragdollarchers.htm" },
  { id: "ragdollhit", title: "Ragdoll Hit", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ragdollhit.html" },
  { id: "ragdollsoccer", title: "Ragdoll Soccer", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/ragdollsoccer.html" },
  { id: "redball4vol1", title: "Red Ball 4 Vol 1", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/redball4vol1.html" },
  { id: "redball4vol2", title: "Red Ball 4 Vol 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/redball4vol2.html" },
  { id: "redball4vol3", title: "Red Ball 4 Vol 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/redball4vol3.html" },
  { id: "retrobowl", title: "Retro Bowl", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/retrobowl.html" },
  { id: "retrobowlcollege", title: "Retro Bowl College", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/retrobowlcollege.html" },
  { id: "retrohighway", title: "Retro Highway", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/retrohighway.html" },
  { id: "retropingpong", title: "Retro Ping Pong", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/retropingpong.html" },
  { id: "riddleschool", title: "Riddle School", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddleschool.html" },
  { id: "riddleschool2", title: "Riddle School 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddleschool2.html" },
  { id: "riddleschool3", title: "Riddle School 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddleschool3.html" },
  { id: "riddleschool4", title: "Riddle School 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddleschool4.html" },
  { id: "riddleschool5", title: "Riddle School 5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddleschool5.html" },
  { id: "riddletransfer", title: "Riddle Transfer", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddletransfer.html" },
  { id: "riddletransfer2", title: "Riddle Transfer 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/riddletransfer2.html" },
  { id: "rocketsoccerderby", title: "Rocket Soccer Derby", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/rocketsoccerderby.html" },
  { id: "rooftopsnipers", title: "Rooftop Snipers", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/rooftopsnipers.htm" },
  { id: "rooftopsnipers2", title: "Rooftop Snipers 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/rooftopsnipers2.html" },
  { id: "run", title: "Run", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/run.html" },
  { id: "run2", title: "Run 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/run2.html" },
  { id: "run3", title: "Run 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/run3.html" },
  { id: "sandgame", title: "Sand Game", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/sandgame.html" },
  { id: "shortlife", title: "Short Life", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/shortlife.html" },
  { id: "ogslope", title: "OG Slope", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/slope.html" },
  { id: "slope2player", title: "Slope 2 Player", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/slope2player.html" },
  { id: "ogslope3", title: "OG Slope 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/slope3.html" },
  { id: "slope3", title: "Slope 3", url: "https://game.azgame.io/slope-3/" },
  { id: "slowroads", title: "Slow Roads", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/slowroads.html" },
  { id: "sm63", title: "Super Mario 63", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/sm63.html" },
  { id: "sm64", title: "Super Mario 64", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/sm64.html" },
  { id: "snowballio", title: "Snowball.io", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/snowballio.html" },
  { id: "snowrider", title: "Snow Rider 3D", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/snowrider.htm" },
  { id: "snowroad", title: "Snow Road", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/snowroad.htm" },
  { id: "soccerbros", title: "Soccer Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/soccerbros.html" },
  { id: "soccerrandom", title: "Soccer Random", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/soccerrandom.htm" },
  { id: "spacebarclicker", title: "Spacebar Clicker", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/spacebarclicker.html" },
  { id: "spaceiskey", title: "Space is Key", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/spaceiskey.html" },
  { id: "spaceiskey2", title: "Space is Key 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/spaceiskey2.html" },
  { id: "spacewaves", title: "Space Waves", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/spacewaves.html" },
  { id: "speedstars", title: "Speed Stars", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/speedstars.html" },
  { id: "sprunki", title: "Sprunki", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/sprunki.html" },
  { id: "stack", title: "Stack", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stack.html" },
  { id: "stacktris", title: "Stacktris", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stacktris.html" },
  { id: "stateio", title: "State.io", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stateio.html" },
  { id: "stickarchersbattle", title: "Stick Archers Battle", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stickarchersbattle.html" },
  { id: "stickfighter", title: "Stick Fighter", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stickfighter.html" },
  { id: "stickmanhook", title: "Stickman Hook", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stickmanhook.html" },
  { id: "stickmerge", title: "Stick Merge", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/stickmerge.html" },
  { id: "subwaysurfersbeijing", title: "Subway Surfers Beijing", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/subwaysurfersbeijing.html" },
  { id: "subwaysurfershavana", title: "Subway Surfers Havana", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/subwaysurfershavana.html" },
  { id: "subwaysurferssanfrancisco", title: "Subway Surfers San Francisco", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/subwaysurferssanfrancisco.html" },
  { id: "superbikethechampion", title: "Super Bike the Champion", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/superbikethechampion.html" },
  { id: "superhot", title: "SUPERHOT", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/superhot.html" },
  { id: "superliquidsoccer", title: "Super Liquid Soccer", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/superliquidsoccer.html" },
  { id: "superstarcar", title: "Superstar Car", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/superstarcar.html" },
  { id: "tabletennisworldtour", title: "Table Tennis World Tour", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/tabletennisworldtour.html" },
  { id: "tag", title: "Tag", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/tag.html" },
  { id: "taproad", title: "Tap Road", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/taproad.html" },
  { id: "templeofboom", title: "Temple of Boom", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/templeofboom.html" },
  { id: "templerun2", title: "Temple Run 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/templerun2.htm" },
  { id: "territorialio", title: "Territorial.io", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/territorialio.html" },
  { id: "theimpossiblequiz", title: "The Impossible Quiz", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/theimpossiblequiz.html" },
  { id: "theimpossiblequiz2", title: "The Impossible Quiz 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/theimpossiblequiz2.html" },
  { id: "thereisnog", title: "There Is No Game", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/thereisnog.html" },
  { id: "theyarecoming", title: "They Are Coming", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/theyarecoming.html" },
  { id: "thisistheonlylevel", title: "This is the Only Level", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/thisistheonlylevel.html" },
  { id: "thisistheonlyleveltoo", title: "This is the Only Level Too", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/thisistheonlyleveltoo.html" },
  { id: "timeshooter2", title: "Time Shooter 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/timeshooter2.html" },
  { id: "timeshooter3", title: "Time Shooter 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/timeshooter3.htm" },
  { id: "tinyfishing", title: "Tiny Fishing", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/tinyfishing.html" },
  { id: "tombofthemask", title: "Tomb of the Mask", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/tombofthemask.htm" },
  { id: "trapthecat", title: "Trap the Cat", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/trapthecat.html" },
  { id: "triviacrack", title: "Trivia Crack", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/triviacrack.html" },
  { id: "tubejumpers", title: "Tube Jumpers", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/tubejumpers.html" },
  { id: "tunnelrush", title: "Tunnel Rush", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/tunnelrush.html" },
  { id: "unicyclehero", title: "Unicycle Hero", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/unicyclehero.html" },
  { id: "vex4", title: "Vex 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vex4.html" },
  { id: "vex5", title: "Vex 5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vex5.html" },
  { id: "vex6", title: "Vex 6", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vex6.htm" },
  { id: "vex7", title: "Vex 7", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vex7.htm" },
  { id: "vex8", title: "Vex 8", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vex8.htm" },
  { id: "vexx3m", title: "Vex X3M", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vexx3m.html" },
  { id: "vexx3m2", title: "Vex X3M 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/vexx3m2.html" },
  { id: "volleyrandom", title: "Volley Random", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/volleyrandom.html" },
  { id: "wartheknights", title: "War the Knights", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wartheknights.html" },
  { id: "webecomewhatwebehold", title: "We Become What We Behold", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/webecomewhatwebehold.html" },
  { id: "wheeliebike", title: "Wheelie Bike", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheeliebike.html" },
  { id: "wheely", title: "Wheely", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely.html" },
  { id: "wheely2", title: "Wheely 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely2.html" },
  { id: "wheely3", title: "Wheely 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely3.html" },
  { id: "wheely4", title: "Wheely 4", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely4.html" },
  { id: "wheely5", title: "Wheely 5", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely5.html" },
  { id: "wheely6", title: "Wheely 6", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely6.html" },
  { id: "wheely7", title: "Wheely 7", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely7.html" },
  { id: "wheely8", title: "Wheely 8", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wheely8.html" },
  { id: "wordleunlimited", title: "Wordle Unlimited", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wordleunlimited.html" },
  { id: "worldshardestgame", title: "World's Hardest Game", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/worldshardestgame.html" },
  { id: "worldshardestgame2", title: "World's Hardest Game 2", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/worldshardestgame2.html" },
  { id: "worldshardestgame3", title: "World's Hardest Game 3", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/worldshardestgame3.html" },
  { id: "wrestlebros", title: "Wrestle Bros", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/wrestlebros.html" },
  { id: "zombierush", title: "Zombie Rush", url: "https://thomasrhys.github.io/Offline-HTML-Games-Pack/offline/zombierush.html" },
]
